# This is a comment
FROM ubuntu
MAINTAINER Noel Burton-Krahn <noel@burton-kahn.com>
# TAG ubuntu-heroku
WORKDIR /app
ADD etc /etc
ADD requirements.* ./
RUN apt-key add /etc/apt/heroku.release.key
RUN apt-get update && apt-get -y install $(cat requirements.apt)
# to install heroku commandline
RUN heroku --help
RUN pip install --upgrade pip && pip install --upgrade -r requirements.txt

