#! /bin/bash
# start snakes 1-8 locally

set -eu

mkdir -p out
for i in $(seq 1 8); do
  SNAKE_NAME="local-$i" PORT="$((5000+i))" heroku local > out/snake-"$i".out 2>&1 &
  echo "$!" > out/snake-"$i".pid
done
